export const tasksData = [
  {
    category: "Work",
    tasks: [
      {
        date: "2025-07-06",
        time: "09:00",
        title: "Team Meeting",
        text: "Discuss project milestones and assign new tasks.",
        isCompleted: false,
      },
      {
        date: "2025-07-07",
        time: "10:30",
        title: "Code Review",
        text: "Review PRs for the authentication module.",
        isCompleted: true,
      },
      {
        date: "2025-07-08",
        time: "14:00",
        title: "Design Feedback",
        text: "Give feedback on the new dashboard mockup.",
        isCompleted: true,
      },
      {
        date: "2025-07-09",
        time: "11:00",
        title: "Deployment",
        text: "Deploy the latest release to staging.",
        isCompleted: false,
      },
      {
        date: "2025-07-10",
        time: "13:30",
        title: "Write Documentation",
        text: "Document new API endpoints.",
        isCompleted: true,
      },
    ],
  },
  {
    category: "Personal",
    tasks: [
      {
        date: "2025-07-08",
        time: "17:00",
        title: "Grocery Shopping",
        text: "Buy ingredients for the weekend dinner party.",
        isCompleted: false,
      },
      {
        date: "2025-07-09",
        time: "18:00",
        title: "Call Mom",
        text: "Catch up and check in on her health.",
        isCompleted: true,
      },
      {
        date: "2025-07-10",
        time: "07:00",
        title: "Exercise",
        text: "Go for a 30-minute run.",
        isCompleted: false,
      },
      {
        date: "2025-07-11",
        time: "10:00",
        title: "Clean Apartment",
        text: "Do laundry and clean the kitchen.",
        isCompleted: false,
      },
      {
        date: "2025-07-12",
        time: "12:00",
        title: "Pay Bills",
        text: "Pay electricity and internet bills.",
        isCompleted: true,
      },
    ],
  },
  {
    category: "Learning",
    tasks: [
      {
        date: "2025-07-07",
        time: "15:00",
        title: "React Tutorial",
        text: "Finish section on useContext and useReducer hooks.",
        isCompleted: false,
      },
      {
        date: "2025-07-10",
        time: "16:30",
        title: "Compiler Notes",
        text: "Revise lexical analysis chapter.",
        isCompleted: false,
      },
      {
        date: "2025-07-11",
        time: "09:30",
        title: "SQL Practice",
        text: "Solve 5 queries from HackerRank.",
        isCompleted: true,
      },
      {
        date: "2025-07-12",
        time: "13:00",
        title: "Watch Tech Talk",
        text: "Watch talk on mobile app security.",
        isCompleted: false,
      },
      {
        date: "2025-07-13",
        time: "20:00",
        title: "Read Blog Post",
        text: "Read latest article on frontend performance.",
        isCompleted: true,
      },
    ],
  },
  {
    category: "Health & Wellness",
    tasks: [
      {
        date: "2025-07-09",
        time: "08:00",
        title: "Drink Water",
        text: "Track 8 cups of water today.",
        isCompleted: true,
      },
      {
        date: "2025-07-10",
        time: "06:30",
        title: "Meditation",
        text: "Practice breathing exercises for 10 minutes.",
        isCompleted: false,
      },
      {
        date: "2025-07-11",
        time: "17:30",
        title: "Meal Prep",
        text: "Prepare healthy meals for the week.",
        isCompleted: false,
      },
      {
        date: "2025-07-12",
        time: "07:30",
        title: "Stretching Routine",
        text: "Do morning and night stretches.",
        isCompleted: true,
      },
      {
        date: "2025-07-13",
        time: "22:00",
        title: "Sleep Tracker",
        text: "Go to bed by 10:30 PM.",
        isCompleted: false,
      },
    ],
  },
];
